# Generated by Django 5.0.6 on 2025-04-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.TextField()),
                ('customer_phone', models.TextField()),
                ('job_date', models.DateField()),
                ('time', models.TextField()),
                ('job_cost', models.TextField()),
                ('job_description', models.TextField()),
                ('additional_notes', models.TextField()),
            ],
        ),
    ]
