# Generated by Django 5.0.6 on 2025-04-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardata',
            name='date_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendardata',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
