# Generated by Django 5.0.6 on 2025-04-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_backend', '0004_alter_calendardata_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendardata',
            old_name='date_text',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='calendardata',
            old_name='notes_extra',
            new_name='cost',
        ),
        migrations.AlterField(
            model_name='calendardata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='calendardata',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendardata',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
