# Generated by Django 5.0.6 on 2025-04-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_backend', '0006_alter_calendardata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardata',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
