# Generated by Django 5.0.6 on 2025-04-14 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_backend', '0007_calendardata_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=255, null=True)),
                ('event_color', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CalendarData',
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='calendar_backend.calendarevents')),
                ('employees_worked', models.CharField(blank=True, max_length=255, null=True)),
                ('hours_worked', models.FloatField(blank=True, null=True)),
                ('client_type', models.CharField(blank=True, max_length=100, null=True)),
                ('client_acquisition', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiscJobs',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='calendar_backend.calendarevents')),
                ('misc_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('misc_notes', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PressureWashingJobs',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='calendar_backend.calendarevents')),
                ('pressure_washing_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('pressure_washing_notes', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WindowsJobs',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='calendar_backend.calendarevents')),
                ('windows_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('windows_notes', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
