# Generated by Django 5.0.6 on 2025-04-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_backend', '0008_calendarevents_delete_calendardata_eventdetails_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventDetails',
        ),
    ]
